## python tutorial 

In [ ]:
1+1

In [ ]:
print("hello world")

In [ ]:
type(1)


In [13]:
first_name='heshan'
last_name='pramuditha'


In [16]:
print("my first name is {} and last name is {}".format(first_name,last_name))

my first name is heshan and last name is pramuditha


In [29]:
type([1,2,4,5,67,])

list

In [30]:
str1="kasun"
str2="20"
str3="USA"
print("My name is {} , I  am {} years old ,I am living {} ".format(str1,int(str2),str3))

My name is kasun , I  am 20 years old ,I am living USA 


In [21]:
my_str="hesh"

print(my_str.isalnum())

## sets

In [26]:
set_var={"high","medium","low"}  #A set means unorderd collection data type 
print(set_var)

{'low', 'medium', 'high'}


In [31]:
#indexing 
set_var.add("extream high")

In [32]:
print(set_var)

{'extream high', 'low', 'medium', 'high'}


## Dictonaries

In [35]:
my_dict={"car_type":"audi"}
print(my_dict)

{'car_type': 'audi'}


In [36]:
# we can add even for loop 
for x in my_dict:
    print(x)

car_type


## Nested 

In [ ]:
car1_model={'Mercdes' : 1960}
car2_model={'audi':1970}
car3_model={'ambessador' : 1980}

car_type={'car1':car1_model, 'car2'}

## Tuple 

In [4]:
# not mutable 
my_tuple=("hesh","pramuditha")
print(my_tuple[0])

hesh


## Numpy


In [7]:
  
import numpy as np 

my_list=[1,2,3,4,5,6]

arr=np.array(my_list)


In [8]:
print(arr)

[1 2 3 4 5 6]


In [9]:
arr.shape 

(6,)

In [10]:
arr[0]

np.int64(1)

In [11]:
print(arr[0])

1


In [22]:
# multinested array 
my_list1=[1,2,3,4,5,6]
my_list2=[3,5,6,8,5,8]
my_list3=[4,5,8,9,2,7]


In [23]:
arr=np.array([my_list1,my_list2,my_list3])

In [24]:
print(arr)

[[1 2 3 4 5 6]
 [3 5 6 8 5 8]
 [4 5 8 9 2 7]]


In [25]:
arr.shape

(3, 6)

In [30]:
arr.reshape(1,18)

array([[1, 2, 3, 4, 5, 6, 3, 5, 6, 8, 5, 8, 4, 5, 8, 9, 2, 7]])

In [27]:
# in 2 dimentional have 2 openening brackets , 1 dinemsional having one opnennig brackets 

# array opertaions are very fast 


## Indexing 

In [40]:
import numpy as np
my_arr=([[1,2,3,4,5,6],[3,5,6,7,8,6]])


arr= np.array(my_arr)


In [41]:
print(arr)

[[1 2 3 4 5 6]
 [3 5 6 7 8 6]]


In [42]:
arr[0:3]

array([[1, 2, 3, 4, 5, 6],
       [3, 5, 6, 7, 8, 6]])

In [45]:
arr[:,:]

array([[1, 2, 3, 4, 5, 6],
       [3, 5, 6, 7, 8, 6]])

In [47]:
my_arr3=([[[6,7,8],[8,9,0],[0,7,4]]])
arr3=np.array([my_arr3])

In [48]:
print(arr3)

[[[[6 7 8]
   [8 9 0]
   [0 7 4]]]]


In [50]:
arr3[1:2:1]

array([], shape=(0, 1, 3, 3), dtype=int64)

In [52]:
arr3[1:,1:]

array([], shape=(0, 0, 3, 3), dtype=int64)